---
################################################
## Kibana install
################################################

- name: Ensure app apt dependencies are installed
  apt: pkg={{item}} state=installed
  with_items:
    - nginx
    - unzip

- name: Ensure Kibana 4.4.x repository is installed
  apt_repository: repo="deb http://packages.elastic.co/kibana/4.4/debian stable main" state=present update_cache=yes

- name: Install Kibana
  apt: pkg=kibana state=installed update_cache=yes

#- name: Ensure /var/www/kibana is deleted
#  file: path=/var/www/kibana state=absent

#- name: Ensure /var/www/kibana is an empty directory
#  file: path=/var/www/kibana state=directory

#- name: Ensure we have the latest release
#  get_url: url={{kibana_url}} dest=/tmp/kibana.zip

#- name: Unzip kibana to /var/www
#  unarchive: src=/tmp/kibana.zip dest=/var/www/ copy=no

#- name: Rename the directory to /var/www/kibana
#  shell: mv /var/www/kibana-master/src/* /var/www/kibana

#- name: Clean up old kibana directory
#  file: path=/var/www/kibana-master state=absent

- name: Ensure kibana's htpasswd file is in place
  copy: src=../roles/kibana/files/htpasswd dest=/etc/nginx/htpasswd mode=0644 owner=root group=root

- name: Ensure default nginx site is not enabled
  file: state=link src=/etc/nginx/sites-available/default path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure kibana nginx site is in place
  copy: src=../roles/kibana/templates/nginx.conf.j2 dest=/etc/nginx/sites-available/kibana

- name: Create a symlink to enable nginx vhost
  file: src=/etc/nginx/sites-available/kibana dest=/etc/nginx/sites-enabled/kibana state=link owner=root group=root
  notify:
    - restart nginx

- name: Ensure kibana config is in place
  template: src=../roles/kibana/templates/config.js.j2 dest=/opt/kibana/config/kibana.yml mode=0644 owner=root group=root
  notify:
    - restart nginx
    - restart kibana